version: '3.7'

services:
  postgres:
    image: postgres:15.1
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5433:5432

volumes:
  postgres-data: